"""Shared helpers for generating subject data files (src/data/*.ts) from Python.

Writing content here and emitting JSON avoids hand-escaping quotes in TypeScript, and lets us
check every question's correct answer really is one of its options.
"""
import json
import io
import os
from collections import Counter

DIFFICULTIES = {'foundation', 'intermediate', 'higher', 'further'}


def q(qid, question, options, correct, explanation, difficulty):
    """A question whose correct answer is given as text; the index is worked out (and checked)."""
    assert difficulty in DIFFICULTIES, (qid, difficulty)
    assert len(options) == 4, (qid, 'needs 4 options')
    assert len(set(options)) == 4, (qid, 'duplicate options')
    assert correct in options, (qid, 'correct answer not in options', correct)
    return {
        'id': qid,
        'question': question,
        'options': options,
        'correctAnswer': options.index(correct),
        'explanation': explanation,
        'difficulty': difficulty,
    }


def topic(tid, unit_id, name, description, explanation, key_points, flashcards, questions):
    for question in questions:
        question['topicId'] = tid
    return {
        'id': tid,
        'unitId': unit_id,
        'name': name,
        'description': description,
        'explanation': explanation.strip(),
        'keyPoints': key_points,
        'flashcards': [{'id': f'{tid}-f{i + 1}', 'front': f, 'back': b} for i, (f, b) in enumerate(flashcards)],
        'videos': [],
        'questions': questions,
    }


def write_subject(path, export_name, subject, header):
    ids = [q['id'] for u in subject['units'] for t in u['topics'] for q in t['questions']]
    dupes = [i for i, n in Counter(ids).items() if n > 1]
    assert not dupes, ('duplicate question ids', dupes)

    positions = Counter(q['correctAnswer'] for u in subject['units'] for t in u['topics'] for q in t['questions'])
    body = json.dumps(subject, ensure_ascii=False, indent=2)
    text = (
        f"// {header}\n"
        "// Generated by scripts/content — edit the Python source there and re-run it rather than editing this file.\n"
        "import type { Subject } from '../types';\n\n"
        f"export const {export_name}: Subject = {body};\n"
    )
    os.makedirs(os.path.dirname(path), exist_ok=True)
    io.open(path, 'w', encoding='utf-8', newline='\n').write(text)

    per_topic = {t['id']: Counter(q['difficulty'] for q in t['questions']) for u in subject['units'] for t in u['topics']}
    print(f"wrote {path}: {len(ids)} questions; answer positions {dict(sorted(positions.items()))}")
    for tid, c in per_topic.items():
        hard = c['higher'] + c['further']
        flag = '' if hard >= 2 else '  <-- fewer than 2 higher/further'
        print(f"  {tid}: {sum(c.values())} q ({dict(c)}){flag}")
